### ISSUE TITLE
Item Retrieval From Container during EVA

### ISSUE THREAD

**Issue by Chrisl154** [KospY/KAS#103]
![ss for all mods and system info](https://cloud.githubusercontent.com/assets/8339835/3789158/77089164-1a8f-11e4-9d82-b446eaf47967.jpg)

Once you have reached orbit, Kerbalnaut goes to container, opens and you press take, nothing comes out. Attempted on several different containers and restarted whilst removing mods

Im unable to send output log here for you.

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (KAS Grab/Storage will be removed and replaced by KIS).
