### ISSUE TITLE
Container weight bug

### ISSUE THREAD

**Issue by Thea70** [KospY/KAS#113]
Bug when loading containers. Bug is reproduced when using symmetry with multiple containers:

1) Place containers using symmetry
2) Load a single container with anything
3) Remove loaded container using symmetry
4) Place back down. All empty containers now have weight of full container but no items.

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (KAS Grab/Storage will be removed and replaced by KIS).
