### ISSUE TITLE
Parts missing from KAS.

### ISSUE THREAD

**Issue by hoffcorp** [KospY/KAS#118]
Many of the parts that I normally would use in KAS aren't available.  Specifically Modular Girder Segment and other girder segments.  Also the rover wheels I can use happen to be limited to the S2.  I can't put these into containers and I can't manipulate them if I attach them in the VAB.

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (KAS Grab/Storage will be removed and replaced by KIS).
