### ISSUE TITLE
Survey stakes from EPL exploding

### ISSUE THREAD

**Issue by Rebelgamer** [KospY/KAS#120]
Kospy, I originally posted this in the EPL issue tracker, but I believe it's more to do with KAS.

For some reason, the survey stakes are exploding at my base on Minmus. Their not destroying anything, just themselves.

First time it happened, I had dropped the stake on the ground(accidentally), and when I went to grab it, it gave me the option to attach. So I did. Boom. Big boom. No damage to the kerbal or anything else, I figured I shouldn't attach a stake that is laying on the ground without grabbing it first.

The second time is stranger. I had 2 stakes layed out, one origin, one Z+, so I could place base sections in the orientation I wanted. After the module was built, I decided to go on a long eva for more science(I did not move the stakes). On my way back, base loaded just fine when I crossed the 2.5km barrier, and for almost a minute after that. When I got within 200m of the base, both stakes exploded(which is rather spectacular considering their just a metal rod).

I'm not going to post my log file, it's over 2m lines because of an issue with a radiator in interstellar.

[LOG 11:03:37.669] [Bildin Kerman Base]: ground contact! - error: 0.001m
[LOG 11:03:37.670] Unpacking Bildin Kerman Base
[LOG 11:03:37.670] [KAS] OnVesselGoOffRails(Core) Re-attach static object
[LOG 11:03:37.671] [KAS] JointToStatic(Base) Create kinematic rigidbody
[LOG 11:03:37.672] [KAS] JointToStatic(Base) Create fixed joint on the kinematic rigidbody
[LOG 11:03:37.701] [Bildin Kerman Base]: ground contact! - error: 0.001m
[LOG 11:03:37.702] Unpacking Bildin Kerman Base
[LOG 11:03:37.702] [KAS] OnVesselGoOffRails(Core) Re-attach static object
[LOG 11:03:37.703] [KAS] JointToStatic(Base) Create kinematic rigidbody
[LOG 11:03:37.704] [KAS] JointToStatic(Base) Create fixed joint on the kinematic rigidbody
[WRN 11:03:44.659] Vessel Bildin Kerman Base crashed through terrain on Minmus
[LOG 11:03:44.660] [00:07:15]: Bildin Kerman Base crashed into Minmus.
[LOG 11:03:44.662] [KSP Interstellar] Handling Impactor
[LOG 11:03:44.664] [KSP Interstellar] Handling Impactor
[LOG 11:03:44.665] ExSurveyStake (Bildin Kerman Base) Exploded!! - blast awesomeness: 0.5
[LOG 11:03:44.668] [ExSurveyStake (Bildin Kerman Base)]: Deactivated
[LOG 11:03:44.669] [EL ST] RemoveStake Bildin Kerman Base Minmus
[LOG 11:03:44.670] [EL ST] isClose 200
[LOG 11:03:44.670] [EL ST] isClose [-100.01253799742, 69.4178895199057, -14.2400182631318] [-100.387158758938, 68.9208225027969, -16.3022384799624] 4.64016855716305 40000
[LOG 11:03:44.671] [EL ST] isClose 200
[LOG 11:03:44.672] [EL ST] isClose [-100.387158758938, 68.9208225027969, -16.3022384799624] [-100.387158758938, 68.9208225027969, -16.3022384799624] 0 40000
[WRN 11:03:44.674] Vessel Bildin Kerman Base crashed through terrain on Minmus
[LOG 11:03:44.675] [KSP Interstellar] Handling Impactor
[LOG 11:03:44.676] [KSP Interstellar] Handling Impactor
[LOG 11:03:44.677] [Explosion] Combined.
[LOG 11:03:44.678] ExSurveyStake (Bildin Kerman Base) Exploded!! - blast awesomeness: 0.5
[LOG 11:03:44.679] [ExSurveyStake (Bildin Kerman Base)]: Deactivated
[LOG 11:03:44.680] [EL ST] RemoveStake Bildin Kerman Base Minmus
[LOG 11:03:44.681] [EL ST] isClose 200
[LOG 11:03:44.681] [EL ST] isClose [-100.387158758938, 68.9208225027969, -16.3022384799624] [-100.01253799742, 69.4178895199057, -14.2400182631318] 4.64016855716305 40000
[EXC 11:03:44.682] NullReferenceException: Object reference not set to an instance of an object
ExLP.ExSurveyTracker+SurveySite.get_Item (Int32 index)
ExLP.ExSurveyStation.get_vessel ()
ExLP.ExBuildControl.onVesselWasModified (.Vessel v)
EventData`1[Vessel].Fire (.Vessel data)
Part.Die ()
Part.explode ()
Vessel.FixedUpdate ()

For now, I'll just pull stakes after done building.

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (KAS Grab/Storage will be removed and replaced by KIS).
