### ISSUE TITLE
GetModuleCost is already additive

### ISSUE THREAD

**Issue by Ramarren** [KospY/KAS#125]
GetModuleCost method on the IPartCostModifier is additive in the sense that the value returned is added to, not replace, the part cost. With the current implementation it doubles the wet cost of every part that includes KASModuleContainer module. This is very noticable for e.g. MKS Pioneer modules. 

The defaultCost argument is there only if the cost modifier is supposed to be based on the existing cost, which doesn't apply in this case.

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (KAS Grab/Storage will be removed and replaced by KIS).
