### ISSUE TITLE
Grabbed Problem

### ISSUE THREAD

**Issue by Viruzzz** [KospY/KAS#128]
Hi,

I wanted to use the Buran Manipulator but is not working after restart the game or back to menu.

![buran_mani](https://cloud.githubusercontent.com/assets/28611/6609841/c0bf718c-c85f-11e4-93b6-aa4667b030ca.png)

i had tried to use and the secondary canadarm but is the same. i can grabbed but i can't moved.
What i can do to working again?!

thx

**Comment by ExtremeTrader** [comment]
- Check if mods are incompatible with each other of with the version of KSP you're using.
- Upload your KSP.log somewhere and post the link.

**Comment by KospY** [comment]
Closing this issue (no news)
