### ISSUE TITLE
No Archive!

### ISSUE THREAD

**Issue by Liquidhalo231** [KospY/KAS#129]
There is no archive of old versions. The ones that are available only go back to version 0.25. Request at least a decent archive for users playing older versions of KSP.

**Comment by KospY** [comment]
Archive of old versions can be found here : http://kerbal.curseforge.com/ksp-mods/223900-kerbal-attachment-system-kas/files (in case you missing it).

There is no archive older than KSP 0.24.2, simply because I lost them when spaceport closed.
I didn't have any backup of this. sorry :(

**Comment by Kerbas-ad-astra** [comment]
I've got KAS on an old 0.23.5 install, if that's of interest.  The DLL says it's version 0.4.7.

**Comment by KospY** [comment]
I'm interested. That's very nice of you ! 
I will archive it as soon as I receive the file.  

Thanks !

**Comment by Kerbas-ad-astra** [comment]
Here you go: http://www.mediafire.com/download/24za2c7rgw2sxr1/KAS_0.4.7_for_KSP_0.23.5.zip

**Comment by KospY** [comment]
I uploaded  KAS 0.4.7 on curse :)
