### ISSUE TITLE
1.0 support.

### ISSUE THREAD

**Issue by zanven42** [KospY/KAS#132]
update to support 1.0? 

i know a lot of people would be wondering and i didn't see a issue raised for people to see its being worked on and when a eta would be so they won't spam the forums :). love the work one of my fav mods.

**Comment by jejacks0n** [comment]
:+1:

**Comment by SkyMarshal** [comment]
The only real issue I have heard about with a naive 1.0 compatibility change was that some parts were not attaching right due to the node changes.

**Comment by nextjr** [comment]
yeah the issue I'm having is the wires/ropes or whatever doesn't extent and retract.

**Comment by KospY** [comment]
KAS 0.5 released :)
