### ISSUE TITLE
Struts

### ISSUE THREAD

**Issue by TechToolbox** [KospY/KAS#135]
The placement of strut end point works fine but when on EVA the only option in the right click menu for the part is "Scrap Part". There is no "Link" option which renders the part unusable. I have tried with all three Kerbal professions and in both career and creative games, the issue occurs in all of them. Enjoy this awesome mod, keep up the great work.

**Comment by TechToolbox** [comment]
These are the mods I have installed: 000_Toolbar, Community Resource Pack, Contracts Window, KAS, USI Koloniation, USI Life Support, USI Exploration, USI FTT, Final Frontier, Infernal Robotics: Rework + Expasnion, MechJeb2, Remote Tech, SCANsat, Stage Recovery

**Comment by KospY** [comment]
Did you tried with the latest version ? Can you provide me the KSP log file ?
