### ISSUE TITLE
KSP stuck loading on KAS_CPort1 with Atomic Age installed

### ISSUE THREAD

**Issue by Teslafly** [KospY/KAS#136]
KSP freezes loading a little over halfway through on KAS/Parts/cport1/part/KAS_CPort1
if Atomic Age is installed https://kerbalstuff.com/mod/744/Atomic%20Age
Ksp and system is still responsive, but you can let it sit for 10 minutes and it doesn't get any further.
uncompatability found by selectively uninstalling mods until loading problem went away. kas and atomic age suspected culprits.

I know you don't have to bake compatibility with other mods into your own, but this one is somewhat popular and may be an easy fix, (don't hold me to that, I know very little about ksp modding) so I'll put this here.

If you need any debug files I'll be happy to provide them

**Comment by atomic1125** [comment]
I can also confirm that KAS_CPort1 stuck, no atomic age installed.

**Comment by RealKolago** [comment]
Me to! Log: https://www.dropbox.com/s/x8hjc5sncga8jv0/output_log2.zip?dl=0

**Comment by RealKolago** [comment]
KIS v1.1.4 solved the problem.
