### ISSUE TITLE
KAS + IR menus not working

### ISSUE THREAD

**Issue by GokouZWAR** [KospY/KAS#140]
When you attach Infernal Robotics parts to ships the Mod parts are not able to be manipulated through the IR menus. They do not appear. Either they don't attach properly for the system to detect them or the mod doesn't understand that they are attached to the part i'm in.

Also when the part is detached it immediately snaps back to the ship (sometimes quite violently, causing explosions). This only appears to occur with IR parts as well as the IR enchanced models and rework parts. 

I'm attempting to assemble a working robotic arm on a space station and a minmus base but without the ability for those parts to work post-launch it kinda defeats the purpose of KAS entirely. I want to be able to build the arm from scratch so i don't have to put a ferring on a launcher to bring the arm into space.

**Comment by KospY** [comment]
InfernalRobotics module crash when the part is created.
Here is the log :

[LOG 21:54:39.943] [KIS] Create part & attach
[LOG 21:54:39.954] Parsing rect
[LOG 21:54:39.954] Parsing rect
[LOG 21:54:39.955] Parsing rect
[LOG 21:54:39.955] Parsing bool
[LOG 21:54:39.955] Parsing bool
[ERR 21:54:39.963] Actor::setLinearVelocity: Actor must be (non-kinematic) dynamic!

[ERR 21:54:39.963] Actor::setAngularVelocity: Actor must be (non-kinematic) dynamic!

[LOG 21:54:39.968] [KIS] CreatePart - Waiting initialization of the part...
[LOG 21:54:39.968] [KIS] StopPointer(pointer)
[LOG 21:54:39.971] IR: Loading sounds : MagicSmokeIndustries/Sounds/infernalRoboticMotor
[LOG 21:54:39.972] IR: Sound successfully loaded.
[EXC 21:54:39.972] NullReferenceException: Object reference not set to an instance of an object
	InfernalRobotics.Module.MuMechToggle.BuildAttachments ()
	InfernalRobotics.Module.MuMechToggle.OnStart (StartState state)
	Part.ModulesOnStart ()
	Part+.MoveNext ()
[EXC 21:54:39.983] ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
	System.Collections.Generic.List`1[FlightIntegrator+OcclusionData].get_Item (Int32 index)
	FlightIntegrator.UpdateOcclusionSolar ()
	FlightIntegrator.UpdateOcclusion ()
	FlightIntegrator.FixedUpdate ()
...repeated in loop...

**Comment by KospY** [comment]
I sent a PM to Sirkut to take a look on this.

**Comment by ZiwKerman** [comment]
FYI: I've added some null checks, but ship still requires reloading after IR parts are attached for them to work properly. It is because we initialize transforms in OnStart method of our Modulue, but when the IR part is spawned by KIS it has no parent, so we cannot do this properly until the part is attached to the ship. Although once it is attached and you do switch from the ship to space centre and then back again everything seem to work properly.

**Comment by ZiwKerman** [comment]
Update: Zodius proposed a good solution and I've implemented it in the latest build: the IR part that is not properly initialized (which happens when it is KIS attached) will start in Locked state and will try to re-initialize on unlock. I've tested with a couple test cases and it seems to work fine.

**Comment by GokouZWAR** [comment]
Ok I'll give that a shot on my stream tonight and I'll see if that works. I've had some parts get offset from IR with some weird time warping so I'll move them and then try a reload to the space center to see if it'll work.

I think the biggest problem will be that mid flight the grouping doesn't get saved. On complex builds that could be an issue.

-GokouZWAR

**Comment by ZiwKerman** [comment]
You'll need a fixed IR build to try, so you'll have to wait until 1.03 comes out (it is when we plan to release the update)

**Comment by GokouZWAR** [comment]
Ok will you let me know on this thread when it's officially out?

-GokouZWAR

**Comment by ZiwKerman** [comment]
Yes, no problem

**Comment by ihsoft** [comment]
In the current state of KIS/KAS and IR they are incompatible. Making them work together is a dedicated huge task.
