### ISSUE TITLE
KJR and KAS Interference

### ISSUE THREAD

**Issue by MInorInconvenience** [KospY/KAS#141]
Not sure if this has been highlighted here, but there is a conflict between KAS and Kerbal Joint Refinforcement.  According to ferram4:

KIS / KAS needs to either fire GameEvents.onPartUndock(Part p) or GameEvents.onVesselWasModified(Vessel v) for the vehicle in question if it's going to change the configuration. This is what stock does when it undocks / modifies / creates a vessel during undocking, and KAS / KIS must follow that unless their goal is to cause a lot of other issues in the game along the way.

See here:
http://forum.kerbalspaceprogram.com/threads/55657-1-0-2-Kerbal-Joint-Reinforcement-v3-1-3-4-27-15/page152

**Comment by KospY** [comment]
I replied to Ferram on the thread about this : http://forum.kerbalspaceprogram.com/threads/55657-1-0-2-Kerbal-Joint-Reinforcement-v3-1-3-4-27-15?p=1985196&viewfull=1#post1985196

**Comment by MInorInconvenience** [comment]
Thanks for looking into this. You are a credit to the mod community.

**Comment by KAmaia** [comment]
posted a similar problem today.
