### ISSUE TITLE
Unable to remove connector ports

### ISSUE THREAD

**Issue by iamsoinsane** [KospY/KAS#145]
I have not been able to narrow down what causes this, but most of the time after i use connector ports to transfer resources around one of the ports are stuck on the craft, and i get this message when trying to remove it.
http://images.akamai.steamusercontent.com/ugc/46506585708886650/2599F1C362D8F4AEEC71CF9EECB696D90E12450E/

"Part cant be grabbed because 1 part is attached to it"..... is this just something I am doing wrong, for as often as it happens to me, I have not found any mentions of it... :(

**Comment by jfranklin** [comment]
I've not had time to test extensively, but I've been experiencing the same issue, and so far it seems to be the connector is break the link from that I end up not being able to remove.

**Comment by space-is-hard** [comment]
I imagine that, upon disconnect, the *child* vessel has its root part reset to the connector port, as that would have been the closest part to the root of the combined vessel before disconnecting.

**Comment by KospY** [comment]
I think space-is-hard is right, the part become the root on undock.
Anyway, I changed the way attach & detach work in the next version of KIS (1.2), so this problem will no more happen ;)
