### ISSUE TITLE
Problem With Winches

### ISSUE THREAD

**Issue by Salclyon** [KospY/KAS#147]
This is a very irritating bug. I ran into when loading my ssto's cargo on the side of the runway.

Steps on how to repeat this bug:
1. Make craft with a winch and something it can connect too, CC-R2 Port, Grappling hook etc.
2. Launch the craft on the runway or launchpad.
3.Have a kerbal attach the winch to a CC-R2 Port, Grappling hook etc.
4.Return to the space center 
5.Go back to the craft you will get the following message  "______ already used!". 
6. Procede to retract or lock the winch you will get the following message "connected parts not aligned docking is impossible!"
7. It doesn't matter if the winch is unplugged or plugged you will repeatedly get this message. You will not be able to retract it.

EDIT: This bug occurs with grappling hooks and electromagnets too, Im assuming anything that the winch attaches too this will happen. 

The only way around this bug is to remove the winch with a kerbal and reattach it.

**Comment by ringerc** [comment]
Oops, I think my issue #148 is the same as this one, I just didn't realise because the title was so generic.

**Comment by Climberfx** [comment]
Almost the same here. The diference here is that i do not need to go back to KSC. IT won't retract at all, even with KIS and KAS on the 1.0.4 latest release. I only be able to use it once in a remote controlled core probe.

**Comment by societalpillage** [comment]
Same problem here, specifically after a quickload. I did find a workaround for this bug though: Going into the save file and finding the "port" part(aka not the winch), changing the "plugged" tag under it's KASModulePort section from True to False and reloading the save seems to reset the attachment connection for some reason. I've only tried this with the cc-r2 port so ymmv.
