### ISSUE TITLE
Feature suggestion: Permit detach without grab for too-heavy objects

### ISSUE THREAD

**Issue by ringerc** [KospY/KAS#149]
Heavy work on craft is presently very hard to co-ordinate, even in microgravity, because a kerbonaut can only grab up to a 1 tonne object. More kerbonauts within grab reach add 1 tonne of carrying capacity each but can be really hard to keep in place, often needing the construction of temporary gantries, addition of handholds, etc.

That's cool and all, but much of the time a sensible construction approach would involve an engineer detaching the part then using a winch and rope (or manipulator arm or whatever) to maneuver the part into the desired location. Or simply application of craft thrust to separate from it after detachment if the part is no longer wanted.

For example, if you land up in orbit with a Mainsail bolted on the back and decide you're willing to go to the trouble of refitting with a Poodle before setting off to Jool, the hard part isn't attaching the Poodle (2 kerbals), but getting the big unwanted engine off (6 kerbals). Careless use of explosives detonated at a distance is not recommended. A 2-man team should be able to unbolt the old engine and winch (or nudge) it out of the way then grab the new one.

So I'd really like to see a way to use a tool to detach an object without grabbing it for pick & place or into inventory. Just decouple it with a tool. This would also make it possible to do things like "break" a craft at a line between two fuel tanks, which is currently just not possible because large tanks weigh too much to get enough kerbals near.

Being able to similarly attach something that's been moved "close enough" to the desired position using winches, etc, would be nice too, so it's possible to move and attach huge fuel tanks in microgravity with a gantry and winches. That's probably separate and more complicated to do though, since it involves detecting when a part is near enough and well enough aligned.

**Comment by ringerc** [comment]
You can detach a Mainsail with enough kerbals, but it sure looks silly!

Approach 1: the cloud of kerbals. 
![Uploading screenshot69.png…](so many) 
![Uploading screenshot71.png…](kerbals)


Approach 2: Move a ladder into place, queue up, and haul!

![Uploading screenshot87.png…](Queue up on a ladder)
![Uploading screenshot89.png…](and haul)

Made more complex by the fact that ladders, despite being small, don't fit in a backpack or even a back-carried container cube because their volume is 1800L or so somehow. So you have to leapfrog it along.

Hence my argument that it might be worth permitting detach-without-grab.

**Comment by ringerc** [comment]
This is an alternative / variant of #146

**Comment by KospY** [comment]
Released KIS 1.2.0 recently. You can now detach any part without grabbing :)

**Comment by ringerc** [comment]
Nicely done, and most kind. Thanks for what you're doing with this mod.

On 12 July 2015 at 03:18, KospY <notifications@github.com> wrote:

> Released KIS 1.2.0 recently. You can now detach any part without grabbing
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KospY/KAS/issues/149#issuecomment-120653305>.
>



-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services
