### ISSUE TITLE
Can't attach anything Radial Attachment Point

### ISSUE THREAD

**Issue by wyand** [KospY/KAS#150]
Parts cannot be attached to the [BZ-52 Radial Attachment Point](http://wiki.kerbalspaceprogram.com/wiki/BZ-52_Radial_Attachment_Point). This was attempted with many small-sized fuel tanks, in KSP 1.0.4 with no mods except KAS and KIS active. The radial attachment point was attached (radially, of course) to a [S3-7200 tank](http://wiki.kerbalspaceprogram.com/wiki/Kerbodyne_S3-7200_Tank).

**Comment by KospY** [comment]
This is a KIS related issue, see https://github.com/KospY/KIS/issues/73
