### ISSUE TITLE
Wire bug

### ISSUE THREAD

**Issue by dtondo** [KospY/KAS#164]
When I tested the mod I saw 2 big bugs....

1) It transpass the ground... in other words, ground is not link ground...
2) The wire is extended to a unknown place, see in the video: 
https://youtu.be/SdeyDwVdV8I

**Comment by ihsoft** [comment]
Try making a clean install. I've seen this bug when two copies of KAS were living in the game.

**Comment by dtondo** [comment]
Hummm 

Do you mena delete KAS from folder GameData and download it and install it again?

Thanks for the tip : )

**Comment by ihsoft** [comment]
I'd suggest dropping all the data except `Squad`, and then re-installing all the mods. Though, you may start from dropping KAS only :)

**Comment by dtondo** [comment]
Yeap Just delete the KAS from folder game data and download it again make it works well D: 

Thanks
