### ISSUE TITLE
Kerbal crash when entering ship after unlinking pipe

### ISSUE THREAD

**Issue by juanman80** [KospY/KAS#192]
As the title says, Kerbal crashes when I reenter the ship after unlinking any of the pipes added after docking. It doesn't matter which pipe I unlink, which kerbal does it or in which module I enter.

Attached you may find kerbal dump and logs. My window locale is spanish and so some errors appear in spanish, I can help translate if needed.
[Kerbal-crash-2016-12-01_162722.ZIP](https://github.com/KospY/KAS/files/625666/Kerbal-crash-2016-12-01_162722.ZIP)

**Comment by ihsoft** [comment]
It looks like a mods conflict issue. Try removing all mods that you can to not break the save file, then try reproducing the issue. Alos, I need `KSP.log` file (it gets overwritten each time the game starts, so capture it right after the crash).

**Comment by juanman80** [comment]
You are right: I've removed everything but KAS and module manager and now it doesn't crash. sorry to bother.

**Comment by ihsoft** [comment]
FYI. If you could figure out which mod causes the conflict I may try fixing it.
