### ISSUE TITLE
Attached Solar Panels fail to power vessel

### ISSUE THREAD

**Issue by CalculusWarrior** [KospY/KAS#54]
Title says it all, when I take the OX-STAT solar panels out of an 'A'-type container and attach them to a probe core, they fail to power the probe core, despite the sun being up and the right-click menu on the solar panel states that they are in fact generating power. I guess my kerbal forgot to hook up the wires properly :P

I remember reading a post somewhere that a similar issue happens with ladders; kerbals cannot climb them after being placed down. Seems like a major issue...

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (Grab/Storage removed).
