### ISSUE TITLE
Items attached to Kerbals are removed on spacecraft entry

### ISSUE THREAD

**Issue by Andon-A** [KospY/KAS#61]
I've fiddled around with attaching some things to Kerbals (To be fair, mostly to see what happens), and I noticed that once you re-enter a spacecraft, if you have something attached to the kerbal, that item is now gone forever. Even if you bring the kerbal out of the craft, the stuff isn't attached to them any further.

**Comment by KospY** [comment]
Cleaning issues not related to the 0.5 version of KAS (KAS Grab/Storage is removed and replaced by KIS).
