### ISSUE TITLE
Physics Negation of Held Objects Results in a Wide Range of Unintended Behavior

### ISSUE THREAD

**Issue by Greys0** [KospY/KAS#72]
When an EVA Kerbal picks up a grabable object, that object's physics are negated to prevent glitchy phantom forces and accidental destruction and so on. This is intended.

As a result of how this is done a lot of edge cases are created where objects or forces get parented onto the physics free object.

The first facet is that anything attached to the PFObject does not impart force against the original Kerbal, and that Kerbal only gains the weight of the part that it has picked up. This effectively breaks the concept of "Equal and opposite forces" and makes all of the force apply to the additional objects, This makes them prone to wobbling and prone to breaking off. By this the Kerbal is capable of lifting unlimited weights, though the joint between those weights and the PFO is not very stable unless the PFO has a very high mass.

The second facet is that generally speaking (read as: There are exceptions) the PFO itself cannot generate forces itself. SRBs made to be held do not generate thrust, wheels do not drive, winches don't pull against the Kerbal. Parachutes however do work, this may be due to them operating via drag instead of a direct force, or it might just be ModuleParachute doing it's own thing.

The third facet is the possible generation of extreme phantom forces. This happens at various points for various reasons with various results, 

There are probably several other facets, and it seems likely that this is the root of many other glitches

**Comment by KospY** [comment]
Cleaning issues not related to the 0.5 version of KAS (KAS Grab/Storage is removed and replaced by KIS).
