### ISSUE TITLE
Unable to cancel links

### ISSUE THREAD

**Issue by Patupi** [KospY/KAS#73]
Primarily tested with pipe links, but probably similar with other EVA linked parts. Once a Kerbal has clicked 'link' to a pipe end connector on a ship there is no way to cancel the link other than to connect to an end point or to board a ship. Once, attempting to find a way around this, I grabbed another part to cancel it... and ended up with a floating green line of the pipe following the Kerbal around, disconnected from him and seeming to drift away, but keeping position (but not orientation) with him as he moved. Odd to say the least.

**Comment by KospY** [comment]
Cleaning old issues
