### ISSUE TITLE
Container GUI can't be closed once opened

### ISSUE THREAD

**Issue by OmagaIII** [KospY/KAS#83]
Has it already been reported?

I haven't found a similar post, no.

Is it intended behavior? / Are you doing it right?

Yip, I right click the container during construction to add items, but once opened I cannot close it. I click close but nothing happens. Same thing happens if a Kerbal tries to access the storage, I cannot remove items at all. I have to either exit the game, or I have to head to launch pad and back to construction.

Is it actually a KAS problem?

It only tends to happen with KAS. My other mods work fine.

Are you up-to-date?

Yip, v 0.4.5

I am using the following mods;

ActionsOnTheFly 1.1.1
B9 Aerospace Pack R4
Kethane v0.8.2
KW Release Package v 2.5.52
MechJeb 2.1.0.0
NovaPunch 2.03a
QuantumStruts 2.0.3
RLA Electric Engines 0.6.1
Squad Texture Pack (Reduce RAM usage)

System spec.

AMD Phenom II X4
8GB RAM
Dual ATI Radeon 5870 in CF
NV GeForce 9600GT (Hybrid Physics)
Windows 7 Ulitmate x64
Manual KSP Download and Install

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (Grab/Storage removed).
