### ISSUE TITLE
Stock parts already attached cannot be grabbed

### ISSUE THREAD

**Issue by Phoenix84** [KospY/KAS#85]
I noticed with the 0.23 update, and corresponding KAS update, I can no longer grab stock parts that were already attached to ships/structures. When I right-click, nothing happens. KAS parts do not exhibit this problem.
If I have a stock part in a storage container I can grab it and place it normally, then even grab it again. However parts that were already attached before upgrading cannot be.

The parts I've tried to interact with are the two lights, the 4-way RCS thruster, the rockomax 24-77, and the fixed solar panel.

This includes parts I placed via KAS under 0.22.

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (KAS Grab/Storage will be removed and replaced by KIS).
