### ISSUE TITLE
Cannot "open" container outside of VAB / SPH

### ISSUE THREAD

**Issue by TBryson2** [KospY/KAS#86]
I can open and fill a container while it is in VAB or SPH, but once outside of the VAB or SPH I cannot open a container without FIRST "grabbing" or removing it from the vessel it is attached to.  (spaceship, rover, ...)

Once it is removed, THEN I can "open" it and retrieve any stored item.  Real problem if I'm working on several satellites and have parts within. I cannot leave the container on my ship and still get into it.

I do not seem to be having any other issues.

Using KSP .23 and KAS 0.4.5

**Comment by KospY** [comment]
Cleaning issues not related to the next version of KAS (Grab/Storage removed).
