### ISSUE TITLE
Fuel transfer not worcking...                  bug?

### ISSUE THREAD

**Issue by filipeiras** [KospY/KAS#93]
![lol](https://cloud.githubusercontent.com/assets/7644364/3026659/86266ea2-e018-11e3-8ac3-e1f1eda49927.jpg)

So i only instaled Kas on ksp to see if the error was becuse other mods butt it isnt... when i link one fuel tank to another there are no keys to clic (out fuel) And( in fuel)  +-.....

So im i doing something wrong?

**Comment by PhildeCube** [comment]
I managed to get it to work through pylons in .090 the other day.

It seems like it works *if* you link from the main tank/ship to the pylon, then from the pylon to another tank/ship. The link order seems to matter. If you find you can't transfer, unlink all connections and the redo them starting at one end, and work your way, in order, to the other.

**Comment by ihsoft** [comment]
I guess it was fixed long time ago.
