### ISSUE TITLE
Stronger KAS Struts

### ISSUE THREAD

**Issue by VasVadum** [KospY/KAS#97]
I'd like some thicker stronger KAS Struts, to reduce part count when needing lots of struts.  Basically a larger connector end and thicker cable.

**Comment by KospY** [comment]
Current strut are too weak because the physic joint is done on both strut part.
If I set the joint on both strut parent part, I think the joint will be a lot stronger.
Don't think that need a new part for this, only fix the current one

**Comment by KospY** [comment]
KAS 0.5 released :)
